version: "3.9"

services:
  app:
    build: .
    image: webxwiz
    environment:
      - DB_URI=mongodb://mongo1:27017/webxwiz?replicaSet=rs0&directConnection=true
    restart: unless-stopped
    command: pnpm run dev
    links:
      - mongo1
    depends_on:
      - mongo1
    networks:
      - app-network
    volumes:
      - .:/src

  mongo1:
    image: mongo
    command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
    ports:
      - 27017:27017
    healthcheck:
      test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'127.0.0.1:27017'}]}) }" | mongosh --port 27017 --quiet # nasty hack for replica set init
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    networks:
      - app-network
    volumes:
      - "mongo1_data:/data/db"
      - "mongo1_config:/data/configdb"

networks:
  app-network:
    driver: bridge

volumes:
  mongo1_data:
  mongo1_config:
